[package]
name = "sha-256"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.82"
fmtastic = "0.2.0"
hex = "0.4.3"
lazy_static = "1.4.0"
num = { version = "0.4.1", features = ["rand"] }
num-traits = "0.2.17"
rand = "0.8"
